import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import ContextApp from '@/context/ContextApp'
import ToDoList from '@/components/ToDoList'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <ContextApp>
          <ToDoList></ToDoList>
        </ContextApp>
      </main>
    </>
  )
}
